### ISSUE TITLE
Please check lines 36 and 43

### ISSUE THREAD

**Issue by den-vasyliev** [vitalibit/security-pre-commit#1]
`Gitleaks is not installed. Installing...

gitleaks: Refusing to overwrite archive

tar: Error exit delayed from previous errors.

Traceback (most recent call last):
  File "<stdin>", line 101, in <module>
  File "<stdin>", line 92, in main
  File "<stdin>", line 43, in install_gitleaks
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['tar', '-xzf', 'gitleaks', 'gitleaks']' returned non-zero exit status 1.`

**Comment by vitalibit** [comment]
Hello, Denys! Thanks for your check. Please specify on which OS and architecture are you running the script?

**Comment by den-vasyliev** [comment]
Hey! Please find my [PR](https://github.com/vitalibit/security-pre-commit/pull/2) please

**Comment by vitalibit** [comment]
Thanks a lot!
